var avatorFile=null;var ic=null;var imgHeight=0;var imgWidth=0;var inEditor=false;var img=null;var minWidth="240";var minHeight="80";var Ratio="3/1"
function previewLoad(e){$("#bgDiv").hide();onEditPic(e);$('#RegisterCardPage').hide();$('#editpic').show();$("#nocancel").attr("onclick","CancelImages('"+e+"')");$("#rEditor").attr("onclick","quiteAvatorEditor('"+e+"')");}
function onEditPic(){inEditor=true;if(avatorFile==null)return true;if(ic==null){img=new Image();img.onload=function(){imgHeight=this.height;imgWidth=this.width;ic=new ImgCropper("bgDiv","dragDiv",avatorFile,{Width:this.width,Height:this.height,containerWidth:$(document.body).width(),containerHeight:$(document.body).height(),Color:"#000",Resize:true,minWidth:minWidth,minHeight:minHeight,Ratio:Ratio,RightDown:"rRightDown",LeftDown:"rLeftDown",RightUp:"rRightUp",LeftUp:"rLeftUp",onload:function(){$("#previewWrapper").css({"width":ic.minWidth+"px","height":ic.minHeight+"px"});}},this)}}
img.src=avatorFile;$("#bgDiv").show();$(".loading").hide();}
function postforme(){$atop=$("#avatorTop").val();$aleft=$("#avatorLeft").val();$aWidth=$("#avatorWidth").val();$Height=$("#avatorHeight").val()}
function resetPreview(p,divWidth){ly$("preview").src=avatorFile;var scale=divWidth/p.Width;var pW={Top:Math.round(p.Top*scale),Left:Math.round(p.Left*scale),Width:divWidth,Height:divWidth};with(ly$("preview").style){display="block";position="absolute";left=0-pW.Left;top=0-pW.Top;width=Math.round(imgWidth*scale);height=Math.round(imgHeight*scale);clip="rect("+(pW.Top)+"px,"+(pW.Left+pW.Width)+"px,"+(pW.Top+pW.Height)+"px,"+pW.Left+"px)"}
$("#avatorTop").val(p.Top);$("#avatorLeft").val(p.Left);$("#avatorWidth").val(p.Width);$("#avatorHeight").val(p.Height)}
function onChangePreview(){$("#preview").attr("src","");$("#previewWrapper").hide();resetPreview(ic.GetPicPos(),$("#previewWrapper").width());}
function quiteAvatorEditor(e){$('#RegisterCardPage').show();onChangePreview();$('#editpic').hide();inEditor=false;postforme();var c=document.getElementById("myCanvas");c.width=parseInt($("#previewWrapper").css("width"));;c.height=parseInt($("#previewWrapper").css("height"));;var ctx=c.getContext("2d");var img=document.getElementById("preview");ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.drawImage(img,$aleft,$atop,$aWidth,$Height,0,0,c.width,c.height);ctx.restore();$("#"+e).attr("src",c.toDataURL("image/jpeg"));}
function CancelImages(e){$('#RegisterCardPage').show();onChangePreview();$('#editpic').hide();inEditor=false;var c=document.getElementById("myCanvas");c.width=$("#preview").width();c.height=$("#preview").height();var ctx=c.getContext("2d");var img=document.getElementById("preview");ctx.drawImage(img,0,0,c.width,c.height);$("#"+e).attr("src",c.toDataURL("image/jpeg"));}
function InputOnchange(e,t,c,b){var inputmyname=e;document.getElementById(e).onchange=function(e){$(".loading").show();EXIF.getData(e.target.files[0],function(){var Orientation=EXIF.getTag(this,"Orientation");var file=e.target.files[0];var fileObj=file;var mpImg=new MegaPixImage(file);var resImg=document.getElementById(t);var nfiles=document.getElementById(inputmyname).value;var mxnfiles=nfiles.match(/%3A11/);if(nfiles=="")
{alert("请上传图片");return false;}
else
{if(mxnfiles=="%3A11"){mpImg.render(resImg,{maxWidth:300,maxHeight:300,quality:c,orientation:Orientation},function(){},b,t);}else{if(!/\.(gif|jpg|jpeg|png|GIF|JPG|PNG)$/.test(nfiles))
{alert("图片类型必须是.gif,jpeg,jpg,png中的一种")
return false;}else{mpImg.render(resImg,{maxWidth:300,maxHeight:300,quality:c,orientation:Orientation},function(){},b,t);}}}});}
if(b==1){$('body').append('<canvas id="myCanvas"  style="border: 1px solid red; margin:0px auto;  position:absolute;  left:0px; right:0px; margin:0px auto; display:none;"></canvas>');$('body').append("<div class='loading'><div class='spinner'><div class='bounce1'></div><div class='bounce2'></div><div class='bounce3'></div></div><p>图片加载中....</p></div>");$('body').append("<div  id=\"RegisterCardPage\" style=\" margin:0px; display:none;\"><div class=\"registerInfo\"><div id=\"previewWrapper\" style=\"position: relative; text-align:left; overflow:hidden; margin: 0px auto; display:none; \"> <img  src=\"\" id=\"preview\"  > </div><input name=\"avatorTop\" id=\"avatorTop\" value=\"\"  type=\"hidden\"><input name=\"avatorLeft\" id=\"avatorLeft\" value=\"\" type=\"hidden\"><input name=\"avatorWidth\" id=\"avatorWidth\" value=\"\" type=\"hidden\"><input name=\"avatorHeight\" id=\"avatorHeight\" value=\"\" type=\"hidden\"></div></div>");$('body').append("<div id=\"editpic\" style=\"display: none;\"><center><div class=\"quitediv\" ><p><span><input value=\"裁剪\" id=\"rEditor\" onclick=\"quiteAvatorEditor();\" class=\"button_quite\"  type=\"button\"></span></p><p><span><input value=\"不裁剪\" id=\"nocancel\" onclick=\"CancelImages();\" class=\"button_quite button_style1\"  type=\"button\"></span></p></div><div style=\"position: relative; overflow: hidden; z-index: 100; background-color: rgb(0, 0, 0,0); \" id=\"bgDiv\"> <div style=\"position: absolute; left: 30px; top: 14px; width: 100px; height: 100px; z-index: 200;\" id=\"dragDiv\"><div id=\"rRightDown\"></div><div id=\"rLeftDown\"></div><div id=\"rRightUp\"></div><div id=\"rLeftUp\"></div><div id=\"rRight\"></div><div id=\"rLeft\"></div><div id=\"rUp\"></div><div id=\"rDown\"></div></div></div></center><p id=\"debugDiv\" style=\"display: none;\"></p></div>");}}